services:
  nextjs:
    build:
      args:
        - BUILD_ENV=prod

  django:
    build:
      args:
        - BUILD_ENV=prod

  nginx:
    build:
      args:
        - BUILD_ENV=staging
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  scheduler:
    build:
      args:
        - BUILD_ENV=prod

  worker:
    build:
      args:
        - BUILD_ENV=prod
